### ISSUE TITLE
Modify the mcx function to include a ctrl_state parameter, 

### ISSUE THREAD

**Issue by AbdullahKazi500** [Classiq/classiq-library#172]
Currently, the mcx function in the classiq quantum circuit library lacks the ability to specify the control state for the multi-controlled X gate explicitly. This limits flexibility in certain quantum algorithm implementations and hardware optimization scenarios where controlling qubits in states other than '1' is advantageous.

Proposed Change:
Modify the mcx function to include a ctrl_state parameter, enabling users to specify the control state of the multi-controlled X gate. This parameter should accept values such as decimal integers or bitstrings (e.g., '1', '0', '01'), defaulting to controlling the '1' state if not provided explicitly.

Expected Behavior:
Upon calling the mcx function, users can pass the ctrl_state parameter to specify the desired control state configuration for the multi-controlled X gate. This enhancement will broaden the functionality of the mcx function, allowing for more precise control over quantum operations and optimizations.

Implementation Details:
Function Modification: Update the mcx function to accept the ctrl_state parameter.
Parameter Handling: Ensure the function correctly interprets and utilizes the ctrl_state parameter, integrating it into the construction of the multi-controlled X gate.
Backward Compatibility: Maintain compatibility with existing usage patterns of the mcx function while introducing the new parameter for enhanced functionality.

@TomerGoldfriend let me know

**Comment by TomerGoldfriend** [comment]
@AbdullahKazi500 Classiq already supports multi-controlled operation on any quantum function, including an X gate, with any controlled state specified via an expression. For example, the following code applies an MCX with the controlled state "010":

```

qfunc main(output target: qbit) {
  qba: qnum;
  allocate<3>(qba);
  allocate<1>(target);
  control (qba==2) {
    X(target);
  }
}

```

See [here](https://docs.classiq.io/latest/reference-manual/platform/qmod/language-reference/statements/control/) for more information.

@AbdullahKazi500 please let us know if this indeed covers your issue.

**Comment by TomerGoldfriend** [comment]
Thank you @AbdullahKazi500 , this is a nice idea. However, currently we cannot accept this function to our open library: The `apply_controlled_x` is too specific and its implementation can be easily achieved via the generic `control` operation. If users would like to use this function they can simply include it in their specific model. For example, in https://github.com/Classiq/classiq-library/issues/56 you can add this function to the specific model in the notebook, rather than the public open library.
