### ISSUE TITLE
A bug in the documentation page

### ISSUE THREAD

**Issue by mitul3737** [Classiq/classiq-library#185]
This page has |8\rangle instead of |8>

Can I work on this?

Thank you
![issue](https://github.com/Classiq/classiq-library/assets/57193846/a8ba3ec7-b445-4fde-9c89-2c9866b11819)

**Comment by heinzay1999** [comment]
There is also a grammatical mistake of "od" in the third sentence. It should be "of" instead of "od"

**Comment by mitul3737** [comment]
> There is also a grammatical mistake of "od" in the third sentence. It should be "of" instead of "od"

Even It was unnoticed for me.

**Comment by orsa-classiq** [comment]
Sure @mitul3737 you can fix that

**Comment by amir-naveh** [comment]
@orsa-classiq , @mitul3737 - is this closed? Anyone working on it? Thanks
