### ISSUE TITLE
Is there any documentation on  MCX (multi-control-x) minimized depth/ minimized width, maximal width / depth ?

### ISSUE THREAD

**Issue by mitul3737** [Classiq/classiq-library#187]
Although we have **MCX function with minimal depth**, there is no documentation to fine tune that.

If that exists, can I get that? If not, can someone guide me to create a documentation on that?

**Comment by orsa-classiq** [comment]
You can find documentation about optimizing circuit depth here:
https://docs.classiq.io/latest/explore/tutorials/classiq_concepts/optimize/optimize/#constraints-and-preferences-in-the-ide

There is no way to control single function depth, but the entire model. So if you want to get a single MCX with minimal depth, create a circuit with MCX only, and optimize the circuit for depth

**Comment by mitul3737** [comment]
> You can find documentation about optimizing circuit depth here: https://docs.classiq.io/latest/explore/tutorials/classiq_concepts/optimize/optimize/
> 
> There is no way to control single function depth, but the entire model. So if you want to get a single MCX with minimal depth, create a circuit with MCX only, and optimize the circuit for depth

Can you please guide me how can I optimize that for max depth/width, minimum depth/width ?

Thank you

**Comment by orsa-classiq** [comment]
you can only optimize for minimum depth\width, not maximum.
use `optimization_parameter='depth'`
