### ISSUE TITLE
Certain LaTeX and images failing to render on Classiq docs

### ISSUE THREAD

**Issue by adam-godel** [Classiq/classiq-library#192]
Hello, I noticed that on many algorithm pages in the Classiq documentation, certain LaTeX expressions wrapped with `$$` do not render properly, even if they render properly in their respective Jupyter notebook in the Classiq library. In addition, certain images are unable to render in the Classiq documentation.

A few examples of this are the first figure in the Introduction section and the matrices in the Quantum Algorithm section on the [Glued Trees page](https://docs.classiq.io/latest/explore/algorithms/glued_trees/glued_trees/), most of the LaTeX in the Technical Notes section on the [Deutsch-Jozsa page](https://docs.classiq.io/latest/explore/algorithms/deutsch_jozsa/deutsch_jozsa/#technical-notes), and much of section 3 of the [HHL page](https://docs.classiq.io/latest/explore/algorithms/hhl/hhl/hhl/#3-modelling-an-hhl-algorithm).

I hope to see a fix to this issue soon!

**Comment by orsa-classiq** [comment]
Thanks @adam-godel !
I see the problem. we will look into it

**Comment by amir-naveh** [comment]
@orsa-classiq - is this issue closed? Thanks

**Comment by orsa-classiq** [comment]
@adam-godel @amir-naveh most of the latex rendering issues will be solved on the next version release.
There is still a problem however with the rendering of the latex matrix of the glued trees notebook that will not be solved by that

**Comment by adam-godel** [comment]
Is there a way to render matrices that will work with the next version release? If so, I could add it to my currently open pull request (#432) making some changes to the notebook.

**Comment by orsa-classiq** [comment]
I will try to find a workaround, we use a framework for the docs that struggles with certain latex expression and it is quite a voodoo

**Comment by amir-naveh** [comment]
@adam-godel - thanks for raising this. For some reason this specific matrix is not rendering properly even after some attempts from our dev team. We'll solve it eventually, but for now I'm closing this issue as it could take a while to resolve. I'll update here once its ready. 
Longer term, I hope more of the documentation code will move to open source, allowing direct resolution of these issues.

**Comment by adam-godel** [comment]
@amir-naveh @orsa-classiq Thanks for letting me know. For now, I have replaced the matrices with image files instead in #432, along with my other changes to the notebook. Please check it out when you have time. I hope to see the issue fixed long term in the future!
