### ISSUE TITLE
Classiq Basics: Quantum Entanglement

### ISSUE THREAD

**Issue by amir-naveh** [Classiq/classiq-library#28]
In this issue, we will create a simple tutorial of quantum entanglement using Classiq. 
This tutorial should follow the structure of the [quantum superpostion tutoria](https://github.com/Classiq/classiq-library/tree/main/community/basic_examples/superposition)l:  
To complete this issue, follow these steps: 
1. Create a new jupyter notebook (.ipynb file). Use any jupyter editor (e.g. jupyter lab, google colab, etc). 
2. Use Classiq's SDK to create the bell state: $|\psi\rangle = \frac{1}{\sqrt{2}} (|00\rangle  + |11\rangle) $. To do this, apply a $H$ (Hadamard) gate to one qubit, and then apply a $CX$ gate controlled on the qubit in superposition. 
3. Similar to the [superposition notebook](https://github.com/Classiq/classiq-library/blob/main/community/basic_examples/superposition/superposition.ipynb), create a short mathematical explanation of the work. Jupyter notebooks support markdown cells, which can contain LaTeX. You can view the source or the superposition notebook to see how this is done. Chat GPT is an excellent LaTeX assistant. 
4. After creating the notebook, make sure you insert the `write_qmod(model, "bell_state.qmod")` line. Run the notebook, and you will automatically generate the .qmod file for this example. 
5. Make sure the notebook looks well, does not have any typos / mistakes, and is running properly.
6. Follow the [contribution guidelines](https://github.com/Classiq/classiq-library/blob/main/CONTRIBUTING.md) to open a pull request. Submit the tutorial to the directory: `classiq-library/community/basic_examples/entanglement`

If you have any questions or comments, you can ask them here in the issue, or in our [slack community](https://short.classiq.io/join-slack), and the Classiq team will be happy to assist. 

Happy quantum coding!

**Comment by maxaakashshinde** [comment]
I can work on this issue would it be able to assign it to me?

**Comment by mahnoor04** [comment]
Has this issue been assigned?

**Comment by jyotiraj-code** [comment]
Hi @amir-naveh I have issued a PR #119 which will close this issue for the UnitaryHack 2024 event

The PR includes:
- A .ipynb file which has the notebook containing the tutorial for creating a quantum entanglement (bell pair) with a comprehensive and student friendly mathematical background of the theory
- A .qmod file is created which is meant to be run on the online platform of classiq
- A .json file is create

It is taken into consideration the PR doesn't have any typo and solves the issue #28 with the proper guidelines and methods as mentioned.

It was good to work on this issue.

**Comment by amir-naveh** [comment]
Hi @jyotiraj-code , thanks for this PR! I will now review, and continue the discussion in the PR.

**Comment by amir-naveh** [comment]
Approved and closed, thank you!
