### ISSUE TITLE
Create a basic tutorial for running a VQE primitive with Classiq

### ISSUE THREAD

**Issue by EdenSchirmanClassiq** [Classiq/classiq-library#34]
The variational quantum eigensolver (VQE) is arguably the most common variational quantum algorithm. As every other quantum algorithm, it can be done easily with Classiq. The goal of this issue is to demonstrate this.

You should create a Jupyter Notebook that implements the same basic VQE algorithm that is demonstrated in [this](https://www.youtube.com/watch?v=EWi5W4X6n0s&list=PL3tmQMGkQcESbwChNUM19yj8hOM6WKLM1&index=5) video from the Classiq Bootcamp 2023. **NOTE** this video follows an old version of Classiq that is not supported anymore, but the idea behind it remains the same.

Concretely, your algorithm should find the minimal energy of the Hamiltonian `Z+0.1X` where `Z` and `X` are the Pauli operators, and the ansatz you should use is a simple `RY` gate.

You can use the[explanation about the Classiq primitives in the user guide](https://docs.classiq.io/latest/user-guide/platform/executor/primitives/) for your help. In addition, feel free to use the [Classiq Slack community](https://short.classiq.io/join-slack) for any question and help.

In order to complete the issue follow the [contribution guidelines](https://github.com/Classiq/classiq-library/blob/main/CONTRIBUTING.md) and enter your adapted notebook to the directory `classiq-library/community/basic_examples/vqe`.

Happy quantum coding!

**Comment by 18001-spec** [comment]
Hi, can this task be assigned to me ?

**Comment by shubhusion** [comment]
@TannerTorrey3 Documentation link mentioned is not working.

**Comment by jyotiraj-code** [comment]
Hi @EdenSchirmanClassiq ! I have released a PR #129 which solves this issue. 

In this PR:
- A detailed comprehensive tutorial has been created which uses the VQE primitive and its parameters to estimate the minimal energy of the Hamiltonian `Z+0.1X` where `Z` and `X` are the Pauli operators, and the ansatz used is a simple `RY` gate
- Easy to understand mathematical background has been created to make the tutorial self sufficient
- The results for the minimal Hamiltonian energy has been compared with the analytical result to draw the accuracy

All the required guidelines and already provided has been used to create the tutorial and it follows the structure of the other tutorials present in the `basic_examples` folder.
