### ISSUE TITLE
Change the Latex use of `\ket{-}` to `|-\rangle` in the phase kickback tutorial

### ISSUE THREAD

**Issue by EdenSchirmanClassiq** [Classiq/classiq-library#38]
In Jupyter notebooks there is the option to write with Latex in the .md cells. This is very convenient as it allows writing mathemtical expressions in a nice format, e.g. $|\psi \rangle = |0\rangle $. These notebooks are the source for the [Classiq documentation](docs.classiq.io). The problem is that for some mathematical expressions written in Latex, the documentation isn't rendered properly. This is the case for the use of \ket{} that is used to represent a ket notation $\ket{}$.

The goal of this issue is to solve this problem for the [phase kickback tutorial](https://github.com/Classiq/classiq-library/blob/main/tutorials/phase_kickback/phase_kickback.ipynb). That is, to change all the appearances of \ket{} to  | followed by \rangle. When rendered in the Jupyter notebook both look the same, but within the [corresponding documentation](https://docs.classiq.io/latest/tutorials/tutorials/phase-kickback/phase-kickback/) it makes a huge difference.

Please follow the contribution guidelines and adapt the phase_kickback.ipynb notebook so it will contain the correct logic of the ket notation but with the use of `|` and `\rangle` instead of `\ket{}`.

**Comment by tejasathalye** [comment]
hey @EdenSchirmanClassiq is the issue still open to work on?

**Comment by Karush2807** [comment]
is it still open to contribute?
if yes--> you can assign to it me :)

**Comment by Shivam250702** [comment]
Hi @EdenSchirmanClassiq , I can work on this issue can you please assign this issue to me

**Comment by pranavmugatkar** [comment]
Hello @EdenSchirmanClassiq  , I am interested in contributing to this issue. Any guidance or specific requirements would be greatly appreciated. Thank you!

**Comment by mukundjha-mj** [comment]
please assign to me

**Comment by EdenSchirmanClassiq** [comment]
Hi all!
Sorry for the confusion, this issue was close and not updated on time.
