### ISSUE TITLE
Refactor the HHL notebook to follow the "Algorithms" structure

### ISSUE THREAD

**Issue by TomerGoldfriend** [Classiq/classiq-library#39]
The goal of this issue is to standardize the HHL notebook to follow a specific structure, to improve its visibility and usability.

There is a general initiative to standardize the `algorithms` directory, putting all notebooks in a specific template. The fixed structure of the notebook allows to deliver the main idea of the algorithm, as well as the rational of high-level modelling with Classiq. Examples can be seen in: [Deutsch Jozsa](https://github.com/Classiq/classiq-library/blob/main/algorithms/bernstein_vazirani/bernstein_vazirani.ipynb), [Bernstein Vazirani](https://github.com/Classiq/classiq-library/blob/main/algorithms/deutsch_jozsa/deutsch_jozsa.ipynb), and [Simon](https://github.com/Classiq/classiq-library/blob/main/algorithms/simon/simon.ipynb) algorithms notebooks.

In this issue the HHL notebook should be rewritten to have the following structure:

- The title should be the name of the algorithm.
- Below the title a short explanation of the algorithm, including its input, promise, and output. Include a figure of the algorithm blocks.
- The sections structure is:
    1. "How to Build the Algorithm with Classiq"
        1.1. "The quantum part" (include all quantum functions)
        1.2. "The classical postprocess" (include all classical post-processing functions)
    2. "Example: exact Hamiltonian evolution"
    3. "Example: approximated Hamiltonian evolution"
    4. "Technical notes"

Further guidelines:
- Go over the already standardized examples mentioned above, to understand the aimed structure of the notebook.
- Heavy technical explanations should be moved to section 4.
- Section 1.1 should include an `hhl` qfunc whose declaration is `hhl( rhs_vector: CArray[float], precision: CInt, hamiltonian_evolution_with_power: QCallable[CInt, QArray[QBit]], res: Output[QArray[QBit]], indicator: Output[QBit])`.
- Section 1.2 should include a pythonic function that gets the execution results and returns the solution vector for the linear equation.
- Section 2 should include defining the Hamiltonian evolution with Classiq's `unitary` built-in function.
- Section 3 should include the decomposition of a matrix to the Pauli basis and the definition of a specific Hamiltonian evolution with Classiq's `suzuki-trotter` built-in function.
- Make sure to generate a qmod (using the `write_qmod` function) for the two different examples.
- Make sure the notebook looks well, does not have any typos / mistakes, and is running properly.
- Follow the [contribution guidelines](https://github.com/Classiq/classiq-library/blob/main/CONTRIBUTING.md) to open a pull request.

If you have any questions or comments, you can ask them here in the issue, or in our [slack community](https://short.classiq.io/join-slack), and the Classiq team will be happy to assist.

Happy quantum coding!

**Comment by TomerGoldfriend** [comment]
@bart-q I am assigning you to this issue.

**Comment by bart-q** [comment]
Yes, please assign me.

**Comment by amir-naveh** [comment]
@TomerGoldfriend - is this issue closed?

**Comment by TomerGoldfriend** [comment]
@amir-naveh a resolving PR by @bart-q was merged recently, but there is an issue with an overwriting commit from our side. Let us wait until the team resolves this before closing the issue.

**Comment by amir-naveh** [comment]
@TomerGoldfriend - great thanks, please update here when resolved.

**Comment by TomerGoldfriend** [comment]
Resolved by https://github.com/Classiq/classiq-library/pull/194. @bart-q thank you for the great work.
