### ISSUE TITLE
Adding Issue template 

### ISSUE THREAD

**Issue by Mayank77maruti** [Classiq/classiq-library#493]
Adding an Issue template so it is easier for both maintainer and contributer to put issues.
please assign this issue to me.

**Comment by orsa-classiq** [comment]
Hi @Mayank77maruti thanks for contributing!
Please write here what is your template suggestion and we will consider

**Comment by Mayank77maruti** [comment]
Hey @orsa-classiq , I have mentioned template for bug report and feature request template. Please do have a look.
