### ISSUE TITLE
Proposal to Improve README Structure

### ISSUE THREAD

**Issue by Vignesh025** [Classiq/classiq-library#494]
The ``README`` file is quite long, and I believe it would be beneficial to create a separate ``INSTALLATION.md`` file for installation instructions. Additionally, I noticed that a ``SECURITY.md`` file is missing, which is important for outlining security practices and reporting vulnerabilities.

I can take the initiative to create both the ``SECURITY.md`` and ``INSTALLATION.md`` files. If you think this is a good idea, please assign me this issue, and I'll get started on it!

**Comment by Vignesh025** [comment]
Hey @atomnoid , I want to work on this issue and also I'm not the maintainer.

**Comment by amir-naveh** [comment]
Hey @Vignesh025 and @atomnoid - I agree the README.md is a bit long, and I'd be happy to see any suggestions for improvements. 

However, I wouldn't want to put the installation separately, its important that it appears in the readme which is visible on the repo homepage. 

What did you have in mind on the security file? 

Thanks

**Comment by atomnoid** [comment]
Hey @amir-naveh we can still improve the some part of readme.md without making any changes in installation part. I agree that the installation part is needed In the readme.md but we can surely improve the structure of the security file. 
I would love to work on this issue please assign this issue to me

**Comment by Vignesh025** [comment]
Hey @amir-naveh, we can include details on how to report security issues and to whom they should be reported in the security file. That would provide a clear process for handling security concerns.

**Comment by amir-naveh** [comment]
Hi @Vignesh025 - thanks for this. Let us consider if these changes are necessary, and then we will decide if we continue on this issue or close it. Thank you.

**Comment by Vignesh025** [comment]
Hi @amir-naveh , sure! Take your time to review, and let me know if you'd like to proceed or close the issue. Thank you!

**Comment by amir-naveh** [comment]
Hi @Vignesh025 - sorry for taking some time here. I think at this stage these change would create more clutter than clarity, so I would prefer to keep them on hold for now. I will close this issue and reopen when these changes could be more relevant in the future. Thank you!

**Comment by Vignesh025** [comment]
Hi @amir-naveh ! No problem at all, that makes sense. Thanks for the update!
