### ISSUE TITLE
Add GitHub Issue Template Schema Form

### ISSUE THREAD

**Issue by utsavdotdev** [Classiq/classiq-library#519]
**Description:**
To streamline the process of creating issues and ensure consistency, we need to add a GitHub issue template schema form. This will help contributors easily provide all the necessary details when reporting bugs, suggesting features, or requesting documentation.

**Requirements:**
1. Create an issue template that includes fields for:
   - Issue Type (Bug, Feature Request,Documentation)
   - Description
   - Steps to Reproduce (for Bug reports)
   - Expected Outcome
   - Additional Context or Screenshots
2. Ensure the template is easy to navigate and fills out the required fields.

**Proposed Changes:**
1. Implement the issue template in `.github/ISSUE_TEMPLATE` folder.
2. Test the template to verify the form fields populate correctly.

**Before and After:**

*Before:*
<img width="978" alt="Screenshot 2024-10-09 at 7 03 35 PM" src="https://github.com/user-attachments/assets/5cf4abc4-6813-4d6a-befa-490f1485cde3">
  
*After:*
<img width="985" alt="Screenshot 2024-10-09 at 7 02 52 PM" src="https://github.com/user-attachments/assets/f3de05cd-db3e-4266-bb7e-9da98f8e6bfc">

**Additional Information:**
If you have any suggestions for extra fields or modifications, please mention them in the comments.

PS: I am willing to submit the Pull Request

**Comment by amir-naveh** [comment]
Hey @utsavdotdev - generally speaking -> you are right. We can start with something simple and see how its being used. What would you recommend as a first step?

**Comment by utsavdotdev** [comment]
I would suggest to use the issue template form with on point text field. For example:

Bug Report:
- Description - Textarea
- Reproduction steps - Textarea
- Expected behavior - Textarea
- Actual Behavior with Screenshots - Textarea
- Operating system - Dropdown
- Provide any additional context for the Bug - Textarea
- Relevant log output - Textarea (Rendered as shell code)
- Have you spent some time to check if this bug has been raised before? - Checkboxes
- Are you willing to submit PR? - Dropdown
- Code of Conduct - Checkboxes (if available)


Feature Request:
- Feature description - Textarea
- Why is this feature needed? - Textarea
- How do you aim to achieve this? - Textarea
- Additional Information - Textarea
- Have you spent some time to check if this feature request has been raised before? - Checkboxes
- Are you willing to submit PR? - Dropdown
- Code of Conduct - Checkboxes (if available)

**Comment by utsavdotdev** [comment]
I would like to raise the pull request this issue after your confirmation
