### ISSUE TITLE
Implement messages to celebrate successful PR contributions

### ISSUE THREAD

**Issue by Mayank77maruti** [Classiq/classiq-library#538]
Provide congratulatory messages when a new contributor submits their first and second PRs or more.

The Solution:-
We will add a GitHub Action that will trigger when a PR gets merged into the main branch.

I would love to implement it.

**Comment by amir-naveh** [comment]
@Mayank77maruti  Good idea, lets do it! 

@TaliCohn @Nadav138 @EdenSchirmanClassiq FYI

**Comment by amir-naveh** [comment]
@Mayank77maruti - assigned you to it together with @Nadav138
