### ISSUE TITLE
Add another implementation for the "increment" function in the discrete quantum walk tutorial

### ISSUE THREAD

**Issue by TomerGoldfriend** [Classiq/classiq-library#56]
The tutorial on [Discrete Quantum Walks](https://github.com/Classiq/classiq-library/blob/main/tutorials/discrete_quantum_walk/discrete_quantum_walk.ipynb) demonstrates an example of a quantum walk on a circle. The `quantum_step_clockwise` quantum function is implemented as a QFT-adder, however, there are other implementations available for such quantum operation, e.g., by applying a cascade of multi-controlled-X gates.

The goal of this issue is to add another implementation for the `quantum_step_clockwise` quantum function in the aforementioned tutorial.

Detailed guidelines:
1. Within the section "Example: Symmetric Quantum Walk on a Circle" in the [notebook](https://github.com/Classiq/classiq-library/blob/main/tutorials/discrete_quantum_walk/discrete_quantum_walk.ipynb) do the following:
   - Add a text explaining that in this example we will construct an implementation for the  "clockwise_step"/"increment" function, which is different from the QFT-based implementation presented above.
   - Add a cell defining a new quantum function with the following declaration: `qfunc increment(x: QArray[QBit])`.
   - Use the new function in the specific example treated in the section.
   - Modify the synthesis constraints: optimize over depth with a relevant constraint over the width.
 2. Under the "Technical Notes" section, add a short explanation about the implementation.
 3. Make sure to generate a qmod (using the write_qmod function) for the modified example.
 4. Make sure the notebook looks well, does not have any typos / mistakes, and is running properly.
 5. Follow the [contribution guidelines](https://github.com/Classiq/classiq-library/blob/main/CONTRIBUTING.md) to open a pull request.

If you have any questions or comments, you can ask them here in the issue, or in our [slack community](https://short.classiq.io/join-slack), and the Classiq team will be happy to assist.

Happy quantum coding!

**Comment by TomerGoldfriend** [comment]
@AbdullahKazi500 Please see the description above. Let us know if you have any questions.

**Comment by TomerGoldfriend** [comment]
Great @AbdullahKazi500 ! let us know if you have any questions.

**Comment by TomerGoldfriend** [comment]
> > Great @AbdullahKazi500 ! let us know if you have any questions.
> 
> Hi can we use auxiliary qubits (qr_aux) when implementing multi-controlled-X gates in Classiq?

You do not need to specify auxiliary qubits explicitly. Classiq supports various implementations for the multi-controlled-X  operation. The implementation, and in particular whether there is a usage of auxiliaries or not, is determined automatically by the synthesis. For example, you can synthesize the following code 

```
qfunc main(output target: qbit) {
  qba: qnum;
  allocate<5>(qba);
  allocate<1>(target);
  control (qba==2) {
    X(target);
  }
}
```

with different optimization/constraints and see that different implementations are chosen.

**Comment by amir-naveh** [comment]
@TomerGoldfriend - is this still in progress or should I close it? Thanks

**Comment by TomerGoldfriend** [comment]
@AbdullahKazi500 could you please give an update? are you planning to work on this?

**Comment by TomerGoldfriend** [comment]
OK, good @AbdullahKazi500 .

**Comment by amir-naveh** [comment]
@TomerGoldfriend - what is the status here? Can we close this?

**Comment by TomerGoldfriend** [comment]
@AbdullahKazi500 no need to upload a partial code. @amir-naveh I am closing this and will reopen when @AbdullahKazi500 
has something to contribute.
