### ISSUE TITLE
Error: 'classiq' not found on import

### ISSUE THREAD

**Issue by applifun** [Classiq/classiq-library#57]
I use Lubuntu  and have created a virtual environment on it. Within this environment, I launched Jupyter Lab. In one of the cells, I executed "!pip install -U classiq", and the installation indicated "success". However, when I attempted to execute "import classiq", I encountered an error stating that "classiq" could not be found. 

Here's how I solved this problem:
1. Execute "!pip show classiq" to check the installation details.
2. Import the sys module with "import sys".
3. Print the list of paths with "print(sys.path)".
    
The issue was that the path listed under "Location" in step 1 wasn't inclueded in the paths from step 3. To resolve this, I added the following line:

4. "sys.path.append('<Path from the Location in step 1>')"

This solution worked well for me, and I hope it can help others facing a similar issue.

**Comment by amir-naveh** [comment]
Thank you @applifun for this feedback!
