### ISSUE TITLE
Add CITATION.bib file referring to Classiq's paper

### ISSUE THREAD

**Issue by amir-naveh** [Classiq/classiq-library#650]
Follow Qiskit's format: 
https://github.com/Qiskit/qiskit/blob/main/CITATION.bib

This is the relevant paper: 
https://arxiv.org/abs/2412.07372

**Comment by ayush-madan** [comment]
Hi, can I be assigned this issue ?

**Comment by ayush-madan** [comment]
This is my first time contributing to open source, any feedback is appreciated :)
