### ISSUE TITLE
resources

### ISSUE THREAD

**Issue by amir-naveh** [Classiq/classiq-library#77]
![classiq logo](https://github.com/Classiq/classiq-library/assets/35042602/743658ec-60c2-4e0f-8f96-ab1eb1caa673)

**Comment by amir-naveh** [comment]
<img width="232" alt="Screenshot 2024-05-22 at 2 00 30" src="https://github.com/Classiq/classiq-library/assets/35042602/743658ec-60c2-4e0f-8f96-ab1eb1caa673">

**Comment by amir-naveh** [comment]
![download (1)](https://github.com/Classiq/classiq-library/assets/35042602/a2f4c564-aa43-4711-83e4-7953e1979f0a)

**Comment by HankNygren** [comment]
![1608032898253](https://github.com/Classiq/classiq-library/assets/172001349/bef5b77c-b717-4962-9a60-e34f4c252a36)

**Comment by amir-naveh** [comment]
![Qiskit Multiply](https://github.com/Classiq/classiq-library/assets/35042602/bd71696f-6067-477c-97de-f0caaf1f14ac)

**Comment by amir-naveh** [comment]
![Classiq Multiply](https://github.com/Classiq/classiq-library/assets/35042602/d11792ba-2e4e-4d4a-86e1-69c8d4a43239)

**Comment by amir-naveh** [comment]
![Qiskit Multiplier](https://github.com/Classiq/classiq-library/assets/35042602/6a939a0c-3aff-4883-8be9-54096d3ee456)

**Comment by amir-naveh** [comment]
![Classiq Multiplier](https://github.com/Classiq/classiq-library/assets/35042602/2cb7e71d-f023-4168-aaba-694cdc7d896c)

**Comment by amir-naveh** [comment]
![3-sat-comparison](https://github.com/Classiq/classiq-library/assets/35042602/cc8687e5-8d34-4fe1-8ac1-5359340d6b09)

**Comment by amir-naveh** [comment]
![Quantum Walk](https://github.com/Classiq/classiq-library/assets/35042602/58e7aaf8-0548-4907-8268-1a38d1b02cf6)

**Comment by amir-naveh** [comment]
![3-sat-comparison](https://github.com/Classiq/classiq-library/assets/35042602/65c3dd4e-3009-4326-b330-9b22a4e876a3)

**Comment by amir-naveh** [comment]
![3-sat-comparison](https://github.com/Classiq/classiq-library/assets/35042602/f1e9aa82-5ed3-4b34-8f49-359833439261)

**Comment by amir-naveh** [comment]
![Fibonacci Oracle Circuit](https://github.com/Classiq/classiq-library/assets/35042602/8d84a9bc-5fb9-46ac-b93a-dd4bd434d181)

**Comment by amir-naveh** [comment]
![Fibonacci Oracle Circuit](https://github.com/Classiq/classiq-library/assets/35042602/4908e8b7-dcc3-444a-9336-8801290557b0)

**Comment by amir-naveh** [comment]
![Fibonacci Oracle LaTeX](https://github.com/Classiq/classiq-library/assets/35042602/66730595-8bad-4a17-973a-1df654add917)

**Comment by amir-naveh** [comment]
![Fibonacci Oracle LaTeX](https://github.com/Classiq/classiq-library/assets/35042602/88098a2e-d867-4945-9d66-309fa2685106)

**Comment by amir-naveh** [comment]
![Fibonacci Oracle LaTeX](https://github.com/Classiq/classiq-library/assets/35042602/d9616587-c42d-443a-9e44-1d7dfe9e2f41)

**Comment by amir-naveh** [comment]
![Fibonacci Oracle State Vector](https://github.com/Classiq/classiq-library/assets/35042602/263c616a-36ab-4949-b954-8d8c7d398c5a)

**Comment by amir-naveh** [comment]
![Hardware Integration](https://github.com/Classiq/classiq-library/assets/35042602/8bd30c56-91cb-4c88-bf07-0d1faf5a2b13)

**Comment by amir-naveh** [comment]
![Supported Cloud Providers](https://github.com/Classiq/classiq-library/assets/35042602/a6bf27e1-f0cb-47d7-8b5b-dd04ff2bad64)

**Comment by amir-naveh** [comment]
![Classiq Github](https://github.com/Classiq/classiq-library/assets/35042602/16244637-5940-49f4-b83e-9bc5ff1441a3)
